#!/usr/bin/env sh
# This is called by `.travis.yml` via Travis CI.
# Only run memory check after Travis complete unit testing

# -e: fail on error
# -v: show commands
# -x: show expanded commands
set -vex

env | sort

# Python is not available in Travis for osx.
#  https://github.com/travis-ci/travis-ci/issues/2320
if [ "$TRAVIS_OS_NAME" != "osx" ]
then
    valgrind --error-exitcode=42 --leak-check=full ./native_test
fi